name: 3dSEBox_withVTK Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.6.0'

    - name: make
      run: make -f /dev/null main
