name: 3dSEBox_withVTK Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - id: Qt
      uses: jurplel/install-qt-action@v3
    - uses: actions/checkout@v1
    - name: make
      run: make -f /dev/null main
